# Generated by Django 2.0.5 on 2018-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='dashboard/default/Coop.png', upload_to='dashboard/%Y/%m/%d'),
        ),
    ]
